a = int(input("Enter first whole number: "))
b = int(input("Enter second whole number: "))
print("Sum:", a + b)
print("Difference:", a - b)
print("Product:", a * b)
print("Quotient:", a / b if b != 0 else "Undefined (division by zero)")
