course = "python programming"
print(len(course))
print(course[0])
print(course[-1])
print(course[0:3])
print(course[0:])
print(course[:3])
print(course[:])
print(course.find("i"))
print(course.replace("p", "j"))
print(course[1:-1])
